apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-b
  namespace: argocd
spec:
  description: Tenant B isolated project
  sourceRepos:
    - '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: tenant-b
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
