apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - policies-app.yaml
  - kyverno-app.yaml
  - tenant-a-app.yaml
  - tenant-b-app.yaml
  - observability-app.yaml
  - platform-config-app.yaml
