apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tenant-b.rbac.yaml
  - tenant-b.resource.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicies/default-deny.yaml
  - networkpolicies/allow-dns-egress.yaml
  - networkpolicies/allow-ingress-from-traefik.yaml
  - networkpolicies/allow-prometheus-scrape.yaml
